### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by samuelrjacobson** [samuelrjacobson/381-Scrum-GitHub-Flow#1]
**User Story**: As a student, I want to be able to see the grades of my submitted assignments, so that I can know where I stand in the class and how to improve on future assignments.

* persona: student who wants to see grades
* feature: grades can be seen online
* business value: knowing my standing in the class

**Task List**
- [ ] Make sure the grades are stored correctly
- [ ] Create HTML views for viewing grades
- [ ] Connect the HTML views to the database/backend to finish the function.

**Acceptance Criteria**
1. only for current semester
2. all classes I'm taking at the moment

**Acceptance Test**
1. The student should be able to view grades for graded assignments.
